Помощь друга
htmlacademy-javascript/61058-keksobooking-25 pull request #12
Opened 2022-03-30 01:15 UTC by lampeduza

2022-03-31 10:40 UTC, iksah requested changes

2022-03-31 10:40 UTC, iksah commented on index.html
> +  <script src="nouislider/nouislider.js"></script>
Отступ лишний

2022-03-31 10:40 UTC, iksah commented on js/ads.js
> +// const adsList = map.querySelector('.map__canvas');
Комменты с лишним кодом лучше сразу удалить

2022-03-31 10:40 UTC, iksah commented on js/map.js
> +});
Лучше обернуть все это в метод setupMap(ads) и вызывать его в main. Тогда и из data не нужно будет экспортировать ads.

2022-03-31 10:40 UTC, iksah commented on js/price-slider.js
> +});
Эти обработчики стоит добавлять при активации страницы и удалить при дезактивации

2022-04-04 12:58 UTC, iksah requested changes

2022-04-04 12:58 UTC, iksah commented on js/map.js
> +disableInterface(deactivateInterfaceFeatures());
Такие вызовы должны быть в main.js

2022-04-04 12:58 UTC, iksah commented on js/form.js
> +const enableInterface = (activateFeatures) => changeInterfaceState(false);
А зачем здесь `activateFeatures`? этот аргумент никак не используется, и не нужен.
Вообще я думал ты сделаешь так:
```js
const changeInterfaceState = (state) => {
   ...
   if (state) {
     addListeners();
   } else {
     removeListeners();
   }
}
```

2022-04-04 12:58 UTC, iksah commented on js/form.js
> +const enableInterface = (activateFeatures) => changeInterfaceState(false);
Вот даже литер ругается (кстати, проверь литером весь проект)

2022-04-04 12:58 UTC, iksah commented on js/map.js
> +  ads.forEach((ad) => {
Вообще я лично ожидал что и весь код выше будет в этой функции (потому что сейчас карта инициализируются при подключении модуля - этот тот сайдэффект о котором мы говорили)

2022-04-05 04:51 UTC, lampeduza commented on js/form.js
> +const enableInterface = (activateFeatures) => changeInterfaceState(false);
А я хотел так сделать

2022-04-05 05:20 UTC, lampeduza commented on js/map.js
> +  ads.forEach((ad) => {
Перенес весь код в setupMap. Там и enabledInterface и disableInterface. Далее, вызвал эту функцию в main.js
Все работает, вроде)

2022-04-05 05:21 UTC, lampeduza commented on js/map.js
> +disableInterface(deactivateInterfaceFeatures());
сделал тернарник в главной функции, из которой выражаем остальные функции

2022-04-05 05:21 UTC, lampeduza commented on js/price-slider.js
> +});
Сделал это тернарником в главной функции

2022-04-05 05:21 UTC, lampeduza commented on js/map.js
> +});
о, а я так и сделал)

2022-04-05 11:17 UTC, iksah commented on js/form.js
> +  enabled ? deactivateInterfaceFeatures() : activateInterfaceFeatures();
Так лучше не делать. Это допускается в функциях `(enabled) => enabled ? a() : b()`, а вот просто в коде нет. Такое сложно читать и разбирать - в полотне кода не поймешь, что тут две разных ветки. Лучше через if-else

2022-04-05 11:20 UTC, iksah commented on js/validation.js
> +import {setupMap} from './map.js';
лишний импорт

2022-04-05 11:35 UTC, merged