Надо подкачаться
htmlacademy-javascript/61058-keksobooking-25 pull request #13
Opened 2022-04-09 18:38 UTC by lampeduza

Сделал pull request раньше времени, почти все написал, кроме обработчиков событий и блокировки кнопки, возврата формы в начальное состояние при ошибке сети. Надеюсь на code review от Сенсея ☯

2022-04-10 06:37 UTC, iksah commented on js/ads.js
> +      const clonedElement = adFeaturesElement.cloneNode(true);
можно не клонировать кстати)

2022-04-10 06:37 UTC, iksah commented on js/api.js
> +const closeMessage = (template) => {
1) Вот тут название не корректное. Мы ведь просто добавляем обработчики, а не закрываем сообщение
2) Лучше расширить showMessage и в нем навешивать обработчики
3) Здесь сделать удаление ноны и удаление обработчиков с документа. И эту функцию вызывать в обработчиках

2022-04-11 07:49 UTC, lampeduza commented on js/ads.js
> +      const clonedElement = adFeaturesElement.cloneNode(true);
ok

2022-04-13 05:59 UTC, iksah requested changes

2022-04-13 05:59 UTC, iksah commented on js/validation.js
> +  getMinimalPrice();
getMinimalPrice надо переименовать, ведь функция ничего не возвращает (get всегда возвращает значение).

2022-04-13 05:59 UTC, iksah commented on js/validation.js
> +  adForm.reset();
Поскольку мы используем эту функцию и при обработке события reset, получается цикл. Юзер кликает по кнопке reset - вызывается сброс формы, а в обработке события сброса - снова вызывается сброс кнопки, который приводит к новому событию reset и так по кругу.

2022-04-13 05:59 UTC, iksah commented on js/validation.js
> +  adForm.reset();
https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/reset

2022-04-13 05:59 UTC, iksah commented on js/validation.js
> +};
обработка браузером события reset происходит после того, как отработают обработчики, и как результат до того, как форма сброшено устанавливается плейсхолдер для старого значения, и только потом форма сбрасывается. И в итоге плейсолдер остается для старого значения, а поле адреса вообще сбрасывается. 
Нужно ил самостоятельно устанавливать дефолтные значения и останавливать дефолтную обработку, или выносить установку значения в следующий цикл обработки событий (например через setTimeout(f, 0))

2022-04-13 06:29 UTC, lampeduza commented on js/validation.js
> +  getMinimalPrice();
done

2022-04-13 15:44 UTC, merged