Нужно больше функций
htmlacademy-javascript/61058-keksobooking-25 pull request #2
Opened 2022-02-20 15:28 UTC by lampeduza

2022-02-20 21:46 UTC, iksah requested changes

2022-02-20 21:46 UTC, iksah commented on js/main.js
> +getRandomFloat(1, 5, 5);
В целом все хорошо, но есть что доработать.
1) В случае ошибки лучше не возвращать строку, а кидать исключение. А ещё лучше не просто исключение, а объект RangeError
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/throw
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError

2) Если вызвать getRandomFloat(1.1, 1.2, 0), то мы всегда получим 1. При этом если вызвать getRandomInteger(1.1, 1.2) - мы получим ошибку, хотя по сути оба вызова делают можно и тоже. Как результат поведение функций получать не консистентным, и может привести к ошибкам при разработке. Подумай, как это можно улучшить.

3) Часть кода в функциях - повторяется. Подумай, можно ли как-то избежать дублирования кода?

Сразу отмечу, что пункт 1 - обязателен к исправлению. Пункты 2 и 3 - не обязательны, но я рекомендую поразмышлять над ними. Это поможет лучше понять некоторые принципы разработки, а так же лучше разобраться в том, как работают программы.

Кстати, очень хорошо, что ты написал вызовы функций. Это первый шаг к написанию юнит-тестов :) Если будет желание, можешь попробовать написать несколько разных вызовов функций - с валидными и не валидными аргументами. Так ты покроешь поведение функции тестами, а изменения кода функции, которые приводят к изменению её поведения, можно будет отловить ещё в процессе разработки.

2022-02-23 10:23 UTC, iksah requested changes

2022-02-23 10:23 UTC, iksah commented on js/main.js
> +  generateError(min, max);
Кажется, что код сгенерирует ошибку  в любом случае. Лучше переименовать эту функцию в checkArguments.

2022-02-23 10:23 UTC, iksah commented on js/main.js
> +const generateError = (min, max) => {
Почему бы не объединить эти две функции (generateNumber, generateError) в одну?

2022-02-23 10:23 UTC, iksah commented on js/main.js
> +const generateNumber = (min, max) => Math.random() * (max - min + 1) + min;
generateRandomNumber

2022-02-23 10:23 UTC, iksah commented on js/main.js
> +};
Смотри, вcе ещё результат не консистентен:
getRandomInteger(1.1, 1.2) => ошибка
getRandomFloat(1.1, 1.2, 0) => 1

Кроме того, 1 меньше чем 1.1

2022-02-23 10:23 UTC, iksah commented on js/main.js
> +getRandomFloat(1, 5, 5);
Кстати, хочу заметить, что в теории `getRandomFloat(a, b, 0)` должен совпадать по значению с `getRandomInteger(a, b)` (при условии, что сгенерировалось одинаковое случайное число) ;)

2022-02-23 10:57 UTC, lampeduza commented on js/main.js
> +};
Да, это диапазон, в которых нет целых чисел

2022-02-23 11:01 UTC, lampeduza commented on js/main.js
> +getRandomFloat(1, 5, 5);
Да, тут можно либо 0 поставить, либо ничего не поставить. Будет тоже самое, что и 0 знаков, после запятой. Я вот тут и думал об этом, чтобы объединить эти 2 функции в одну

2022-02-23 21:06 UTC, iksah requested changes

2022-02-23 21:06 UTC, iksah commented on js/main.js
> +  return Math.random() * (max - min + 1) + min;
Вот смотри. Раньше у нас была функция generateError, но мы хотели её переименовать в checkArguments - потому что она не всегда генерирует ошибку, а только после проверки аргументов.
Теперь у нас почему то после проверки аргументов возвращается какое-то число - это опять не совпадает с названием функции. Теперь это просто getRandomNumber, в котором есть проверки условий.

2022-02-23 21:06 UTC, iksah commented on js/main.js
> +  }
Чтобы расширить это решение для любого amountOfSymbolsAfterComma (кстати, это ещё называется digits), можно значения min и max привести к нужному числу знаков после запятой:

```javascript
const numToFixed = (num, digits) => +num.toFixed(digits);

const getRandomFloat = (min, max, digits = 0) => {
  const min = numToFixed(min, digits);
  const min = numToFixed(min, digits);

  checkArguments(poweredMin, poweredMax);

  const randomNumber = Math.random() * (max - min + 1) + min;
  return numToFixed(randomNumber);
}

const getRandomInteger = (min, max) => getRandomFloat(min, max, 0);
```

Ты и делал это до этого - просто с помощью math.floor

2022-02-23 21:06 UTC, iksah commented on js/main.js
> +  }
И есть альтернативный вариант:
```javascript
const getRandomFloat = (min, max, digits = 0) => {
  const multiplier = 10 ** digits;
  const multipliedMin = Math.floor(min * power);
  const multipliedMax = Math.floor(max * power);

  checkArguments(poweredMin, poweredMax);

  const randomNumber = Math.floor(Math.random() * (max - min + 1) + min);
  return randomNumber / multiplier;
}

const getRandomInteger = (min, max) => getRandomFloat(min, max, 0);
```

Кода чуть больше, но зато меньше конвертаций чисел в строки и назад.

2022-02-23 21:07 UTC, iksah commented on js/main.js
> +  return Math.random() * (max - min + 1) + min;
Здесь конечно я малость тебя запутал своими комментариями, но старайся следить за именованием функций, и чтобы из названия четко прослеживалось, что она будет делать.

2022-02-23 22:08 UTC, merged