Отрисуй меня полностью (часть 1)
htmlacademy-javascript/61058-keksobooking-25 pull request #8
Opened 2022-03-10 17:26 UTC by lampeduza

2022-03-11 14:54 UTC, iksah requested changes

2022-03-11 14:54 UTC, iksah commented on js/ads.js
> +	for (let i = 0; i <= similarAds.length - 1; i++) {
Здесь было бы круто использовать for..of
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Statements/for...of

2022-03-11 14:54 UTC, iksah commented on js/ads.js
> +     		return 'Отель';
Проверять через if-else не очень удобно - это и много кода, и тяжело в поддержке.
1) Можно сделать switch-case https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/switch
2) Можно сделать словарик - объект в котором ключ - это текст на английском, а значение - перевод на русский `{'palace': 'Дворец'}`

Плюс смотри, ты ждешь как аргумент некий список, но не используешь его. 
Ну и для переноса на уровень выше тебе стоит подумать, как подругому ты можешь дать функции знать, какие объекты она может использовать.

2022-03-11 14:54 UTC, iksah commented on js/ads.js
> +    		return 'гостей';
Забегая немного вперед: есть ещё вот такое значение "Не для гостей" (https://up.htmlacademy.ru/javascript/25/project/keksobooking#keksobooking-3-6)

2022-03-11 14:54 UTC, iksah commented on js/ads.js
> +		const adAvatar = ad.querySelector('.popup__avatar').src = similarAds[i].author.avatar;
Кажется ве созданные переменные не используются, так что можно их не объявлять, а просто задать нужные значения.

2022-03-11 14:54 UTC, iksah commented on js/ads.js
> +			}
Хорошо, но можно чуть лучше (я просто оставлю ссылку на разные способы и их описания https://stackoverflow.com/questions/3955229/remove-all-child-elements-of-a-dom-node-in-javascript).

Я рекомендую посмотреть про while.firstChild метод)

2022-03-11 19:20 UTC, lampeduza commented on js/ads.js
> +			}
А тут еще можно же не просто удалять эти children, а сделать проверку на модификатор, а остальные элементы просто удалить? Так не будет лучше?

2022-03-13 09:47 UTC, iksah commented on js/ads.js
> +  adsList.appendChild(adsListFragment);
1) `adFeatures` - название функции, а значит нужен глагол.
2) `generateAds` сейчас всегда добавляют одни и те же объявления (из `similarAds`). А что, если мы захотим добавить другие? Давай сделаем список объявлений аргументом функции.
3) Ты создаешь `ad` вне цикла, потом n-раз обновляешь этот элемент, а затем один раз добавляешь его во фрагмент. Получается что во фрагмент будет добавлен один элемент с данными последнего объявления. Кажется что-то не так :)
4) `adFeatures` добавляет элементы в один и тот же фрагмент. Что, если мы вызовем эту функцию второй раз?

2022-03-13 09:48 UTC, iksah commented on js/data.js
> +  for (let i = 0; i < 1; i++) {
А почему 1?

2022-03-13 09:48 UTC, iksah commented on js/data.js
>    const objectsArray = [];
Вот здесь кстати не нужно пиcать Array, просто objects

2022-03-13 20:22 UTC, iksah requested changes

2022-03-13 20:22 UTC, iksah commented on js/ads.js
> +  for (let j = 0; j <= similarAd.offer.features.length - 1; j++) {
Давай перепишем на for...of

2022-03-13 20:22 UTC, iksah commented on js/ads.js
> +const switchEngToRus = (ad, similarAd) => {
А зачем здесь `ad`?

2022-03-13 20:22 UTC, iksah commented on js/ads.js
> +const getRightRoomsPronunciation = (ad, similarAd) => {
И здесь `ad` - лишний

2022-03-13 20:22 UTC, iksah commented on js/ads.js
> +  for (let j = 0; j <= similarAd.offer.photos.length - 1; j++) {
И здесь давай сделаем for...of

2022-03-13 20:22 UTC, iksah commented on js/ads.js
> +};
А зачем нам генерировать весь список этих объявлений, если мы все равно обрисовывает только одно? Давай тогда просто generateAd(ad) и все. Или даже не generate, а например renderAd.

2022-03-13 20:22 UTC, iksah commented on js/ads.js
> +const similarAds = getObjects();
Давай лучше мы в main.js сгенерируем эти данные, и там же их и используем.
В таком случае если у нас будут файлы с функциями, и main.js, где мы пишем основной исполняемый код. Иначе представь - придется во все другие файлы импортировать этот, хотя он с ними никак не связан.

2022-03-13 22:52 UTC, merged